#!/usr/bin/env python

import eua_control
import rospy


if __name__ == '__main__':
    rospy.init_node('eua_control', disable_signals=True)
    controller = eua_control.EUAController()
    controller.run()
