#!/usr/bin/env python

"""
Bring Dynamixel servos with the given IDs to their center position.

Usage example:

    ./zero_servos /dev/ttyACM0 1000000 --device-ids 1 2 3 4
"""

from __future__ import division, print_function

import argparse
import dynamixel
import numpy as np


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('port')
    parser.add_argument('baudrate', type=int)
    parser.add_argument('-d','--device-ids', nargs='+', type=int, required=True, help='Device IDs')
    args = parser.parse_args()

    chain = dynamixel.Chain(args.port, args.baudrate, args.device_ids)

    if not chain.devices:
        raise RuntimeError("No devices found")

    if len(chain.devices) != len(args.device_ids):
        raise RuntimeError("Not all devices found")

    limits = [(dev.read_param_single('cw_angle_limit'), dev.read_param_single('ccw_angle_limit')) for dev in chain.devices]
    center = [lo + (hi - lo) / 2 for lo, hi in limits]

    for dev, q in zip(chain.devices, center):
        dev.write_param_single('goal_position', q)
