<?xml version="1.0"?>

<!-- da Vinci Large Needle Driver (LND) models -->
<robot name="dv_large_needle_driver" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- End-effector of the LND -->
  <xacro:macro name="dv_large_needle_driver_tip" params="prefix length" >
    <link name="${prefix}rotation">
      <visual>
        <origin xyz="0 0 -0.01" rpy="0 0 ${pi/2}" />
        <geometry>
          <mesh filename="package://mops_description/meshes/lnd_tip/roll.stl" />
        </geometry>
        <material name="tip_metallic_gray" />
      </visual>
    </link>

    <link name="${prefix}wrist">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 ${pi/2}" />
        <geometry>
          <mesh filename="package://mops_description/meshes/lnd_tip/wrist.stl" />
        </geometry>
        <material name="tip_metallic_gray" />
      </visual>
    </link>

    <link name="${prefix}jaw_hinge" />

    <link name="${prefix}jaw0" />

    <link name="${prefix}jaw1">
      <visual>
        <origin xyz="0 0 0" rpy="0 ${pi/2} 0" />
        <geometry>
          <mesh filename="package://mops_description/meshes/lnd_tip/jaw.stl" />
        </geometry>
        <material name="tip_metallic_gray" />
      </visual>
    </link>

    <link name="${prefix}jaw2">
      <visual>
        <origin xyz="0 0 0" rpy="0 ${pi/2} 0" />
        <geometry>
          <mesh filename="package://mops_description/meshes/lnd_tip/jaw.stl" />
        </geometry>
        <material name="tip_metallic_gray" />
      </visual>
    </link>

    <link name="${prefix}tcp0" />

    <link name="${prefix}tcp1" />

    <link name="${prefix}tcp2" />

    <joint name="${prefix}roll" type="revolute">
      <parent link="${prefix}base" />
      <child link="${prefix}rotation" />
      <origin xyz="${length} 0 0" rpy="${-pi} ${-pi/2} 0" />
      <axis xyz="0 0 1" />
      <limit lower="${radians(-260)}" upper="${radians(260)}" effort="0.3" velocity="${2*pi}" />
    </joint>

    <joint name="${prefix}pitch" type="revolute">
      <parent link="${prefix}rotation" />
      <child link="${prefix}wrist" />
      <origin xyz="0 0 0" rpy="${-pi/2} ${-pi/2} 0" />
      <axis xyz="0 0 1" />
      <limit lower="${radians(-80)}" upper="${radians(80)}" effort="0.25" velocity="${2*pi}" />
    </joint>

    <joint name="${prefix}jaw_hinge_fixed" type="fixed">
      <parent link="${prefix}wrist" />
      <child link="${prefix}jaw_hinge" />
      <origin xyz="0.0091 0 0" rpy="${pi/2} 0 0" />
    </joint>

    <!-- This is not a real physical joint, but rather yaw0 = (yaw1 - yaw2) / 2,
          ie. the TCP frame is at an angle between the grasper jaws. -->
    <joint name="${prefix}yaw0" type="revolute">
      <parent link="${prefix}jaw_hinge" />
      <child link="${prefix}jaw0" />
      <origin xyz="0 0 0" rpy="0 0 0" />
      <axis xyz="0 0 1" />
      <limit lower="${radians(-75)}" upper="${radians(75)}" effort="0.2" velocity="${2*pi}" />
    </joint>

    <joint name="${prefix}yaw1" type="revolute">
      <parent link="${prefix}jaw_hinge" />
      <child link="${prefix}jaw1" />
      <origin xyz="0 0 0" rpy="0 0 0" />
      <axis xyz="0 0 1" />
      <limit lower="${radians(-75)}" upper="${radians(75)}" effort="0.2" velocity="${2*pi}" />
    </joint>

    <joint name="${prefix}yaw2" type="revolute">
      <parent link="${prefix}jaw_hinge" />
      <child link="${prefix}jaw2" />
      <origin xyz="0 0 0" rpy="${pi} 0 0" />
      <axis xyz="0 0 1" />
      <limit lower="${radians(-75)}" upper="${radians(75)}" effort="0.2" velocity="${2*pi}" />
    </joint>

    <joint name="${prefix}tcp0_fixed" type="fixed">
      <parent link="${prefix}jaw0" />
      <child link="${prefix}tcp0" />
      <origin xyz="0.009 0 0" rpy="0 0 0" />
    </joint>

    <joint name="${prefix}tcp1_fixed" type="fixed">
      <parent link="${prefix}jaw1" />
      <child link="${prefix}tcp1" />
      <origin xyz="0.009 0 0" rpy="0 0 0" />
    </joint>

    <joint name="${prefix}tcp2_fixed" type="fixed">
      <parent link="${prefix}jaw2" />
      <child link="${prefix}tcp2" />
      <origin xyz="0.009 0 0" rpy="0 0 0" />
    </joint>

  </xacro:macro> <!-- dv_large_needle_driver_tip -->



  <!--  -->
  <xacro:macro name="dv_large_needle_driver_housing_si" params="prefix" >
    <link name="${prefix}housing">
      <visual>
        <geometry>
          <box size="0.096 0.065 0.03" />
        </geometry>
        <material name="housing_light_blue" />
      </visual>
    </link>

    <joint name="${prefix}housing_fixed" type="fixed">
      <parent link="${prefix}base" />
      <child link="${prefix}housing" />
      <origin xyz="-0.025 0 0" rpy="0 0 0" /> <!-- FIXME -->
    </joint>
  </xacro:macro> <!-- dv_large_needle_driver_housing_si -->



  <xacro:macro name="dv_large_needle_driver_housing_xi" params="prefix" >
    <link name="${prefix}housing">
      <visual>
        <geometry>
          <box size="0.06 0.045 0.08" />
        </geometry>
        <material name="housing_white" />
      </visual>
    </link>

    <joint name="${prefix}housing_fixed" type="fixed">
      <parent link="${prefix}base" />
      <child link="${prefix}housing" />
      <origin xyz="-0.015 0 -0.019" rpy="0 0 0" /> <!-- FIXME -->
    </joint>
  </xacro:macro> <!-- dv_large_needle_driver_housing_xi -->



  <xacro:macro name="dv_large_needle_driver_rod" params="prefix length" >
    <link name="${prefix}rod">
      <visual>
        <geometry>
          <cylinder radius="0.004" length="${length}" />
        </geometry>
        <material name="rod_dark_grey" />
      </visual>
    </link>

    <joint name="${prefix}rod_fixed" type="fixed">
      <parent link="${prefix}rotation" />
      <child link="${prefix}rod" />
      <origin xyz="0 0 ${-length/2 - 0.01}" rpy="0 0 0" />
    </joint>
  </xacro:macro> <!-- dv_large_needle_driver_rod -->



  <xacro:macro name="dv_large_needle_driver_420006" params="prefix parent *origin">
    <xacro:property name="length" value="0.4670" />

    <link name="${prefix}base" />

    <joint name="${prefix}base_fixed" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}" />
      <child link="${prefix}base" />
    </joint>

    <xacro:dv_large_needle_driver_tip prefix="${prefix}" length="${length}" />
    <xacro:dv_large_needle_driver_rod prefix="${prefix}" length="${length}" />
    <xacro:dv_large_needle_driver_housing_si prefix="${prefix}" />
  </xacro:macro> <!-- dv_large_needle_driver_420006 -->



  <xacro:macro name="dv_large_needle_driver_470006" params="prefix parent *origin">
    <xacro:property name="length" value="0.5335" />

    <link name="${prefix}base" />

    <joint name="${prefix}base_fixed" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}" />
      <child link="${prefix}base" />
    </joint>

    <xacro:dv_large_needle_driver_tip prefix="${prefix}" length="${length}" />
    <xacro:dv_large_needle_driver_rod prefix="${prefix}" length="${length}" />
    <xacro:dv_large_needle_driver_housing_xi prefix="${prefix}" />
  </xacro:macro> <!-- dv_large_needle_driver_470006 -->

</robot>
