# UR5e + EUA-Xi (v2) + LND 470006 (1)

# Transformation from UR robot TCP to surgical tool TCP
robot_to_tool:
  xyz:
    - 0.09
    - 0
    - 0.62
  rpy:
    - 0
    - -1.570796326795
    - 3.14159265359
