world_to_a_base_link:
  xyz:
    - 0
    - 0.4
    - 0
  rpy:
    - 0
    - 0
    - !degrees 90

world_to_b_base_link:
  xyz:
    - 0
    - -0.4
    - 0
  rpy:
    - 0
    - 0
    - !degrees 90

world_to_stereo_optical:
  xyz:
    - 0.2
    - 0
    - 0.1
  rpy:
    - !degrees -135
    - 0
    - !degrees -90
